### ISSUE TITLE
Tried to add a new task and assign it to a user:

### ISSUE THREAD

**Issue by stevejburge** [AllediaWordPress/UpStream#600]
This is on the frontend of a site, when adding a new Task.

This problem does not happen if you add both a Start Date and End Date for the Task

`Fatal error: Uncaught Error: Call to a member function format() on boolean in /homepages/3/d744581382/htdocs/clickandbuilds/CPS-Club/wp-content/plugins/upstream/includes/up-general-functions.php:532 Stack trace: #0 /homepages/3/d744581382/htdocs/clickandbuilds/CPS-Club/wp-content/plugins/upstream-frontend-edit/includes/class-up-frontend-process.php(890): upstream_date_unixtime('') #1 /homepages/3/d744581382/htdocs/clickandbuilds/CPS-Club/wp-content/plugins/upstream-frontend-edit/includes/class-up-frontend-process.php(800): UpStream_Frontend_Process->add_edit_frontend_item() #2 /homepages/3/d744581382/htdocs/clickandbuilds/CPS-Club/wp-includes/class-wp-hook.php(286): UpStream_Frontend_Process->form_processing('') #3 /homepages/3/d744581382/htdocs/clickandbuilds/CPS-Club/wp-includes/class-wp-hook.php(310): WP_Hook->apply_filters(NULL, Array) #4 /homepages/3/d744581382/htdocs/clickandbuilds/CPS-Club/wp-includes/plugin.php(453): WP_Hook->do_action(Array) #5 /homepages/3/d744581382/htdocs/clickandbuilds/CPS-Club/wp-settings.ph in /homepages/3/d744581382/htdocs/clickandbuilds/CPS-Club/wp-content/plugins/upstream/includes/up-general-functions.php on line 532`

**Comment by stevejburge** [comment]
Fixed in 1.20.2
